### ISSUE TITLE
Fails to start when Firebase App already configured.  

### ISSUE THREAD

**Issue by zacharyrote** [Telerik-Verified-Plugins/Firebase-Invites#8]
I have a fix for this but am unable push my branch and request a PR. Permissions of course
 << see below >>

- (BOOL)application:(UIApplication *)application swizzledDidFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [self application:application swizzledDidFinishLaunchingWithOptions:launchOptions];
    if([FIRApp defaultApp] == nil){
        [FIRApp configure];
    }
    return YES;
}

Forked and submitted PR for this change.

**Comment by EddyVerbruggen** [comment]
Thank you!
